version: '3.8'

services:
  # --- 1. Database (Virtuoso)
  store:
    image: openlink/virtuoso-opensource-7:latest
    container_name: dbpedia-virtuoso
    environment:
      DBA_PASSWORD: "mysecretpassword"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://dbpedia.org"
      VIRT_Parameters_NumberOfBuffers: 170000
      VIRT_Parameters_MaxDirtyBuffers: 130000
      VIRT_Parameters_DirsAllowed: "., /database/to_load"
    ports:
      - "8890:8890"
      - "1111:1111"
    volumes:
      - ./dbpedia_data:/database/to_load
      - ./virtuoso_db:/database

  # --- 2. Backend (Go API) 
  api:
    build: ./dbpedia-backend
    container_name: dbpedia-backend
    ports:
      - "8080:8080"
    environment:
      - VIRTUOSO_ENDPOINT=http://store:8890/sparql
    depends_on:
      - store

  # --- 3. Frontend (React) 
  frontend:
    build:
      context: ./dbpedia-frontend/dbpedia-frontend
    container_name: dbpedia-frontend
    ports:
      - "5173:5173"
    volumes:
      # για (Hot Reload)
      - ./dbpedia-frontend/dbpedia-frontend:/app
      # Προστατεύουμε τα node_modules του container
      - /app/node_modules
    environment:
      #  για να δουλεύει το Hot Reload στα Windows
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api